### ISSUE TITLE
Fast Trace 不进行 Traceroute nasaboy  #131 (comment) 

### ISSUE THREAD

**Issue by sjlleo** [nxtrace/Ntrace-core#132]
```
ubuntu@kr:~$ sudo ./nexttrace -F
NextTrace v1.1.7-1 2023-06-04T03:55:17Z 2c86f86
Hi，欢迎使用 Fast Trace 功能，请注意 Fast Trace 功能只适合新手使用
因为国内网络复杂，我们设置的测试目标有限，建议普通用户自测以获得更加精准的路由情况
请您选择要测试的 IP 类型
1. IPv4
2. IPv6
请选择选项：1
您想测试哪些ISP的路由？
1. 国内四网
2. 电信
3. 联通
4. 移动
5. 教育网
请选择选项：2
[NextTrace API] prefered API IP - [2606:4700:3030::6815:34ee] - 1.09ms
您将默认使用ICMP协议进行路由跟踪，如果您想使用TCP SYN进行路由跟踪，可以加入 -T 参数
```
在国外vps上执行以后，没有进行下一步的测试，这个问题是在哪里？

_最初由 nasaboy 在 https://github.com/sjlleo/nexttrace-core/issues/131#issuecomment-1578266483 发布_

**Comment by nasaboy** [comment]
在多个vps上测试，发现在aws-sg的服务器用的debian11测试成功，可以往下走流程，但是在oracle-kr的机器上是Ubuntu22就有问题，我不确定是哪个导致的问题。

**Comment by sjlleo** [comment]
麻烦您试着 nexttrace  ipv4.pek-4134.nexttrace-io-fasttrace-endpoint.win

我怀疑是域名解析的问题

**Comment by nasaboy** [comment]
> 

这个测试正常

**Comment by sjlleo** [comment]
> > 
> 
> 在oracle-kr上测试正常

这个问题似乎有点奇怪🤔，一般不大会在那里会卡住的样子，只是在测试 IPv4 的时候会这样吗，还是说不管是 IPv4 还是 IPv6 的 Fast Trace 都会卡住～

**Comment by nasaboy** [comment]
ipv4和ipv6都一样。

**Comment by sjlleo** [comment]
> ipv4和ipv6都一样，这个没有debug mode吗？help里好像没有看到

Hi nasaboy,

这个问题已经确定，最近在对 NextTrace 进行彻底地重构，待重构完毕以后这个问题也会解决~

Thanks!

Best Regards,
Leo Shen
