### ISSUE TITLE
HE 就是垃圾

### ISSUE THREAD

**Issue by modhzgu** [nxtrace/Ntrace-core#139]
只能绕美的垃圾线路 用上测速依托答辩 发了帖子还不服气 怕不是收了钱

**Comment by tsosunchia** [comment]
你是不是发错地方了，这里跟HE有什么关系？😅

**Comment by stydxm** [comment]
he跟nexttrace什么关系？发了什么帖子？

**Comment by sjlleo** [comment]
> 只能绕美的垃圾线路 用上测速依托答辩 发了帖子还不服气 怕不是收了钱

笑死了，你自己说的只要是上 HE Transit 全是要跑路的，都不买，最后被人挖出来买了 WikiHost IPv6 和 Centerhop，那这些按你话说都是垃圾咯，那还买了干什么，快去申请退款啊，我真害怕你会被商家坑了呢😱😱😱

**Comment by modhzgu** [comment]
发一条多少钱 有钱一起赚

**Comment by tsosunchia** [comment]
> 发一条多少钱 有钱一起赚

这里是NextTrace，不是云计算/VPS商家，你来这里狗叫什么？

**Comment by modhzgu** [comment]
全员he精神股东 被人骂还不乐意是吧

**Comment by stydxm** [comment]
> 全员he精神股东 被人骂还不乐意是吧

搞清楚，这是开源项目issue，不是客服工单

**Comment by tsosunchia** [comment]
> 全员he精神股东 被人骂还不乐意是吧

HE跟NextTrace没有任何关系，你骂他垃圾是你的自由，但是随地大小便就是没素质了

**Comment by chitang233** [comment]
我在网上买了一瓶可口可乐 难喝 于是我去商场里对着卖螺丝刀的销售员大骂一通

**Comment by AiNEKY** [comment]
什么大脑萎缩发育缺失的脑残废物，，宁是没地方泄愤了吗来一个毫不相干的开源项目issues里丢粪，，宁这种废物应该要被开全户丢到赛博灵堂全网示众，，

**Comment by iambaolong** [comment]
但是这里是issue

**Comment by origami-owo** [comment]
烙子有点什么大病
