### ISSUE TITLE
API 服务器故障

### ISSUE THREAD

**Issue by UptonEdward** [nxtrace/Ntrace-core#143]
此为特殊情况，故不按照模板填写

刚刚本地运行 nexttrace 发现 api 服务器连接失败，后经测试确认是 api 服务器下线（以下为多个海外服务器的测试结果）
```
➜  ~ nexttrace 1.1.1.1
NextTrace v1.1.7-2 2023-06-06T19:36:22Z b1edef3
[NextTrace API] prefered API IP - [2606:4700:3030::ac43:cd76] - 0.89ms
2023/06/22 15:57:28 dial: websocket: bad handshake
IP Geo Data Provider: LeoMoeAPI
traceroute to 1.1.1.1, 30 hops max, 52 bytes packets
2023/06/22 15:57:28 dial: websocket: bad handshake
2023/06/22 15:57:28 dial: websocket: bad handshake
2023/06/22 15:57:29 dial: websocket: bad handshake
1   103.47.x.x  ASAPI Server Error                  局域网          
                                              0.95 ms / 0.46 ms / 0.69 ms
2023/06/22 15:57:29 dial: websocket: bad handshake
2023/06/22 15:57:29 dial: websocket: bad handshake
2   36.255.56.48    ASAPI Server Error                  局域网          
                                              1.19 ms / 5.61 ms / 1.32 ms
3   172.71.212.2    ASAPI Server Error                  局域网          
                                              1.05 ms / 3.66 ms / 4.68 ms
2023/06/22 15:57:31 dial: websocket: bad handshake
4   1.1.1.1         ASAPI Server Error                  局域网          
                                              23.20 ms / 19.42 ms / 22.02 ms
MapTrace URL: 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x754f94]

goroutine 1 [running]:
github.com/gorilla/websocket.(*Conn).Close(0xc00007fac8?)
	github.com/gorilla/websocket@v1.5.0/conn.go:345 +0x14
github.com/xgadget-lab/nexttrace/cmd.Excute.func1()
	github.com/xgadget-lab/nexttrace/cmd/cmd.go:165 +0x25
github.com/xgadget-lab/nexttrace/cmd.Excute()
	github.com/xgadget-lab/nexttrace/cmd/cmd.go:315 +0x1ef3
main.main()
	github.com/xgadget-lab/nexttrace/main.go:8 +0x17

```

**Comment by charlescao460** [comment]
Same here QaQ
![image](https://github.com/nxtrace/Ntrace-core/assets/33741854/19bc9a97-c631-4225-b6b6-6a525c38732a)

**Comment by sjlleo** [comment]
1. 如果新版连不上，不要用新版，1.1.2 才是稳定版本
2. api.leo.moe 国内被 ws 阻断了，建议自行反代

以上问题解决方案都已在其他 issue 有提到，谢谢

**Comment by toyo2333** [comment]
> 1. 如果新版连不上，不要用新版，1.1.2 才是稳定版本
> 2. api.leo.moe 国内被 ws 阻断了，建议自行反代
> 
> 以上问题解决方案都已在其他 issue 有提到，谢谢

小白来问一句，第一次用这种工具，结果里，时间有三列，这三列的意思是什么呢？

然后就是每一行（跳），那个时间是不是相当于秒表里面 打点。到最后一行那个时间就是两个节点直接ping的总用时？（我不知道是不是ping，还是其他什么连接，不懂）

盼望您能解答，谢谢

**Comment by sjlleo** [comment]
> > 1. 如果新版连不上，不要用新版，1.1.2 才是稳定版本
> > 2. api.leo.moe 国内被 ws 阻断了，建议自行反代
> > 
> > 以上问题解决方案都已在其他 issue 有提到，谢谢
> 
> 小白来问一句，第一次用这种工具，结果里，时间有三列，这三列的意思是什么呢？
> 
> 然后就是每一行（跳），那个时间是不是相当于秒表里面 打点。到最后一行那个时间就是两个节点直接ping的总用时？（我不知道是不是ping，还是其他什么连接，不懂）
> 
> 盼望您能解答，谢谢

Hi,

这篇文章详细介绍了 NextTrace 功能，可供您参考
https://blog.linux-code.com/articles/thread-2311.html

Thanks!

**Comment by toyo2333** [comment]
> > > 1. 如果新版连不上，不要用新版，1.1.2 才是稳定版本
> 
> > > 2. api.leo.moe 国内被 ws 阻断了，建议自行反代
> 
> > > 
> 
> > > 以上问题解决方案都已在其他 issue 有提到，谢谢
> 
> > 
> 
> > 小白来问一句，第一次用这种工具，结果里，时间有三列，这三列的意思是什么呢？
> 
> > 
> 
> > 然后就是每一行（跳），那个时间是不是相当于秒表里面 打点。到最后一行那个时间就是两个节点直接ping的总用时？（我不知道是不是ping，还是其他什么连接，不懂）
> 
> > 
> 
> > 盼望您能解答，谢谢
> 
> 
> 
> Hi,
> 
> 
> 
> 这篇文章详细介绍了 NextTrace 功能，可供您参考
> 
> https://blog.linux-code.com/articles/thread-2311.html
> 
> 
> 
> Thanks!

感谢 会用了。之前我还喷了开发者有bug 实在不应该。 自己没搞清楚而已。

**Comment by Leao9203** [comment]
> > 1. 如果新版连不上，不要用新版，1.1.2 才是稳定版本
> > 2. api.leo.moe 国内被 ws 阻断了，建议自行反代
> > 
> > 以上问题解决方案都已在其他 issue 有提到，谢谢
> 
> 小白来问一句，第一次用这种工具，结果里，时间有三列，这三列的意思是什么呢？
> 
> 然后就是每一行（跳），那个时间是不是相当于秒表里面 打点。到最后一行那个时间就是两个节点直接ping的总用时？（我不知道是不是ping，还是其他什么连接，不懂）
> 
> 盼望您能解答，谢谢

三个时间分别为 Average 平均延迟 / Worst 最差延迟 / Best 最佳延迟

**Comment by tsosunchia** [comment]
> 此为特殊情况，故不按照模板填写
> 
> 刚刚本地运行 nexttrace 发现 api 服务器连接失败，后经测试确认是 api 服务器下线（以下为多个海外服务器的测试结果）
> 
> ```
> ➜  ~ nexttrace 1.1.1.1
> NextTrace v1.1.7-2 2023-06-06T19:36:22Z b1edef3
> [NextTrace API] prefered API IP - [2606:4700:3030::ac43:cd76] - 0.89ms
> 2023/06/22 15:57:28 dial: websocket: bad handshake
> IP Geo Data Provider: LeoMoeAPI
> traceroute to 1.1.1.1, 30 hops max, 52 bytes packets
> 2023/06/22 15:57:28 dial: websocket: bad handshake
> 2023/06/22 15:57:28 dial: websocket: bad handshake
> 2023/06/22 15:57:29 dial: websocket: bad handshake
> 1   103.47.x.x  ASAPI Server Error                  局域网          
>                                               0.95 ms / 0.46 ms / 0.69 ms
> 2023/06/22 15:57:29 dial: websocket: bad handshake
> 2023/06/22 15:57:29 dial: websocket: bad handshake
> 2   36.255.56.48    ASAPI Server Error                  局域网          
>                                               1.19 ms / 5.61 ms / 1.32 ms
> 3   172.71.212.2    ASAPI Server Error                  局域网          
>                                               1.05 ms / 3.66 ms / 4.68 ms
> 2023/06/22 15:57:31 dial: websocket: bad handshake
> 4   1.1.1.1         ASAPI Server Error                  局域网          
>                                               23.20 ms / 19.42 ms / 22.02 ms
> MapTrace URL: 
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x754f94]
> 
> goroutine 1 [running]:
> github.com/gorilla/websocket.(*Conn).Close(0xc00007fac8?)
> 	github.com/gorilla/websocket@v1.5.0/conn.go:345 +0x14
> github.com/xgadget-lab/nexttrace/cmd.Excute.func1()
> 	github.com/xgadget-lab/nexttrace/cmd/cmd.go:165 +0x25
> github.com/xgadget-lab/nexttrace/cmd.Excute()
> 	github.com/xgadget-lab/nexttrace/cmd/cmd.go:315 +0x1ef3
> main.main()
> 	github.com/xgadget-lab/nexttrace/main.go:8 +0x17
> ```

1.1.7-x不能使用：
后端问题，不知什么原因退出了，没再起来

现在重新启动，已经正常了
