### ISSUE TITLE
API炸了

### ISSUE THREAD

**Issue by ahhfzwl** [nxtrace/Ntrace-core#145]
![image](https://github.com/nxtrace/Ntrace-core/assets/54196143/613b90e0-2f81-491e-bd85-97bd2f9d8f89)

**Comment by isyekong** [comment]
使用的版本号是什么？

1. 如果新版连不上，不要用新版，1.1.2 才是稳定版本
2. api.leo.moe 国内被 ws 阻断了，建议自行反代

以上问题解决方案都已在其他 issue 有提到，谢谢

**Comment by toyo2333** [comment]
> 使用的版本号是什么？
> 
> 1. 如果新版连不上，不要用新版，1.1.2 才是稳定版本
> 2. api.leo.moe 国内被 ws 阻断了，建议自行反代
> 
> 以上问题解决方案都已在其他 issue 有提到，谢谢

1，同样的问题，使用的是1.1.2版本，前几天还能用的。另外，反代解决api这个。。对于普通用户太难了。我折腾了半天，没法弄好。你们有别的技术手段解决这个问题么比如API走CDN？普通用户完全搞不了。


2，看了之前的其他issue，我个人觉得-M 参数应该默认打开（即默认禁用tracemap功能不上传个人路由信息），如果只是为了方便看路径，最多默认把-P参数带上，输出path就够了。

---关于这一点，如果是从推广工具的角度，我能理解，毕竟结果一点击就有个漂亮截图，方便分享和炫耀，这个的受益方是工具本身，但忽略的是个人对于隐私的关切，当然你也可以说你可以去“自己改代码”或者带参数运行什么的或者滚去别的工具，但“默认选择的”是什么，本身代表了利益相关和价值观。希望你们能重新考虑这个决定。


以上纯个人观点。就工具本身来说是挺棒的，输出界面也好看清晰明了。

只是现在彻底没法用了。

**Comment by toyo2333** [comment]
> > 使用的版本号是什么？
> > 
> > 1. 如果新版连不上，不要用新版，1.1.2 才是稳定版本
> > 2. api.leo.moe 国内被 ws 阻断了，建议自行反代
> > 
> > 以上问题解决方案都已在其他 issue 有提到，谢谢
> 
> 1，同样的问题，使用的是1.1.2版本，前几天还能用的。另外，反代解决api这个。。对于普通用户太难了。我折腾了半天，没法弄好。你们有别的技术手段解决这个问题么比如API走CDN？普通用户完全搞不了。
> 
> 2，看了之前的其他issue，我个人觉得-M 参数应该默认打开（即默认禁用tracemap功能不上传个人路由信息），如果只是为了方便看路径，最多默认把-P参数带上，输出path就够了。
> 
> ---关于这一点，如果是从推广工具的角度，我能理解，毕竟结果一点击就有个漂亮截图，方便分享和炫耀，这个的受益方是工具本身，但忽略的是个人对于隐私的关切，当然你也可以说你可以去“自己改代码”或者带参数运行什么的或者滚去别的工具，但“默认选择的”是什么，本身代表了利益相关和价值观。希望你们能重新考虑这个决定。
> 
> 以上纯个人观点。就工具本身来说是挺棒的，输出界面也好看清晰明了。
> 
> 只是现在彻底没法用了。

很多人选择Ntrace最初始的动机就是：认为其他xxxTrace可能会上传路由数据，希望寻找一个更纯粹安全的服务。

**Comment by peterchop** [comment]
> > 使用的版本号是什么？
> > 
> > 1. 如果新版连不上，不要用新版，1.1.2 才是稳定版本
> > 2. api.leo.moe 国内被 ws 阻断了，建议自行反代
> > 
> > 以上问题解决方案都已在其他 issue 有提到，谢谢
> 
> 1，同样的问题，使用的是1.1.2版本，前几天还能用的。另外，反代解决api这个。。对于普通用户太难了。我折腾了半天，没法弄好。你们有别的技术手段解决这个问题么比如API走CDN？普通用户完全搞不了。
> 
> 2，看了之前的其他issue，我个人觉得-M 参数应该默认打开（即默认禁用tracemap功能不上传个人路由信息），如果只是为了方便看路径，最多默认把-P参数带上，输出path就够了。
> 
> ---关于这一点，如果是从推广工具的角度，我能理解，毕竟结果一点击就有个漂亮截图，方便分享和炫耀，这个的受益方是工具本身，但忽略的是个人对于隐私的关切，当然你也可以说你可以去“自己改代码”或者带参数运行什么的或者滚去别的工具，但“默认选择的”是什么，本身代表了利益相关和价值观。希望你们能重新考虑这个决定。
> 
> 以上纯个人观点。就工具本身来说是挺棒的，输出界面也好看清晰明了。
> 
> 只是现在彻底没法用了。

唉，哥们放弃吧，我朋友和我说这个作者对有asn的朋友态度一直很好，到现在都是有求必应，自从他们站api连ws阻断以后，明显感觉就放弃我们普通用户了，我记得他们这样开销挺大的，不恰饭这么大用户群体确实很难做下去，可能是不愿意再搞但碍于面子迫不得已吧，只能说后面祝他们好运了。

**Comment by toyo2333** [comment]
> > > 使用的版本号是什么？
> > > 
> > > 1. 如果新版连不上，不要用新版，1.1.2 才是稳定版本
> > > 2. api.leo.moe 国内被 ws 阻断了，建议自行反代
> > > 
> > > 以上问题解决方案都已在其他 issue 有提到，谢谢
> > 
> > 
> > 1，同样的问题，使用的是1.1.2版本，前几天还能用的。另外，反代解决api这个。。对于普通用户太难了。我折腾了半天，没法弄好。你们有别的技术手段解决这个问题么比如API走CDN？普通用户完全搞不了。
> > 2，看了之前的其他issue，我个人觉得-M 参数应该默认打开（即默认禁用tracemap功能不上传个人路由信息），如果只是为了方便看路径，最多默认把-P参数带上，输出path就够了。
> > ---关于这一点，如果是从推广工具的角度，我能理解，毕竟结果一点击就有个漂亮截图，方便分享和炫耀，这个的受益方是工具本身，但忽略的是个人对于隐私的关切，当然你也可以说你可以去“自己改代码”或者带参数运行什么的或者滚去别的工具，但“默认选择的”是什么，本身代表了利益相关和价值观。希望你们能重新考虑这个决定。
> > 以上纯个人观点。就工具本身来说是挺棒的，输出界面也好看清晰明了。
> > 只是现在彻底没法用了。
> 
> 唉，哥们放弃吧，我朋友和我说这个作者对有asn的朋友态度一直很好，到现在都是有求必应，自从他们站api连ws阻断以后，明显感觉就放弃我们普通用户了，我记得他们这样开销挺大的，不恰饭这么大用户群体确实很难做下去，可能是不愿意再搞但碍于面子迫不得已吧，只能说后面祝他们好运了。

不太懂这一行的玩法，有“ASN的朋友” 对他们有什么帮助和收益呢？放弃“普通用户”，那这个工具能服务哪些用户呢？ 还请指教。

**Comment by peterchop** [comment]
> 不太懂这一行的玩法，有“ASN的朋友” 对他们有什么帮助和收益呢？放弃“普通用户”，那这个工具能服务哪些用户呢？ 还请指教。

俺只是个玩🐔的，有廉价🐔就抢抢，具体我也不太懂，没玩过，但是有哥们和我说过有asn的都是这个圈子里的顶级玩家，运营商都有自己的asn，好像很多商家也有，反正玩起来非常烧钱。
放弃咱这种我也不知道是为了啥，可能是开销大精力不足吧，也可能他们兴趣早就不在这上面去做更对他们有用的东西去了，但是好在服务端好像代码都开了，希望能有大佬做个镜像顺便改进一下。

**Comment by ahhfzwl** [comment]
> 使用的版本号是什么？
> 
> 1. 如果新版连不上，不要用新版，1.1.2 才是稳定版本
> 2. api.leo.moe 国内被 ws 阻断了，建议自行反代
> 
> 以上问题解决方案都已在其他 issue 有提到，谢谢

![image](https://github.com/nxtrace/Ntrace-core/assets/54196143/f595d051-1ed7-426c-a2a7-9e9a33733566)
程序貌似不允许自定义数据库地址，只能指定 IPAPI.com 作为数据库。

**Comment by toyo2333** [comment]
试了-d参数指定其他ip数据库api都没用。

**Comment by sjlleo** [comment]
已知不可抗力的问题，see https://github.com/nxtrace/Ntrace-core/issues/144#issuecomment-1627533415

**Comment by toyo2333** [comment]
> 已知不可抗力的问题，see [#144 (comment)](https://github.com/nxtrace/Ntrace-core/issues/144#issuecomment-1627533415)



ip的api用不了，那就别用啊。直接输出结果都输出不了么？ 把AS编号输出出来不就得了。再不行只要ip本身都做不到么？

绘制不了地图就不干了？这摆烂摆的。

**Comment by sjlleo** [comment]
> > 已知不可抗力的问题，see [#144 (comment)](https://github.com/nxtrace/Ntrace-core/issues/144#issuecomment-1627533415)
> 
> ip的api用不了，那就别用啊。直接输出结果都输出不了么？ 把AS编号输出出来不就得了。再不行只要ip本身都做不到么？
> 
> 绘制不了地图就不干了？这摆烂摆的。

因为LeoMoeAPI是我自己的API，你的话真搞笑，现在是我自己的域名因为提供了这个ip地理位置这个服务被墙了，导致nexttrace在国内无法正常工作，请问聪明的你我该怎么解决？再说你与我又非甲方乙方的客户关系，无论如何，我都不需要保证它一定可用吧？我只能说当下做开源用爱发电的处境是这样的。

**Comment by toyo2333** [comment]
> > > 已知不可抗力的问题，see [#144 (comment)](https://github.com/nxtrace/Ntrace-core/issues/144#issuecomment-1627533415)
> > 
> > 
> > ip的api用不了，那就别用啊。直接输出结果都输出不了么？ 把AS编号输出出来不就得了。再不行只要ip本身都做不到么？
> > 绘制不了地图就不干了？这摆烂摆的。
> 
> 因为LeoMoeAPI是我自己的API，你的话真搞笑，现在是我自己的域名因为提供了这个ip地理位置这个服务被墙了，导致nexttrace在国内无法正常工作，请问聪明的你我该怎么解决？再说你与我又非甲方乙方的客户关系，无论如何，我都不需要保证它一定可用吧？我只能说当下做开源用爱发电的处境是这样的。

对对对，双向选择。
