### ISSUE TITLE
Was v1.1.7-1 retagged?

### ISSUE THREAD

**Issue by p-linnane** [nxtrace/Ntrace-core#151]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. We noticed that the shasum for v1.1.7-1 of nexttrace has changed. We wanted to verify this is legitimate before updating it in our repository. Thanks!

Relates to https://github.com/Homebrew/homebrew-core/pull/139427.

**Comment by tsosunchia** [comment]
https://github.com/Homebrew/homebrew-core/pull/139427 
There is no problem with this commit, thanks.
