### ISSUE TITLE
在Windows平台上使用时如果采用本地dns服务nexttrace会报错

### ISSUE THREAD

**Issue by HXHGTS** [nxtrace/Ntrace-core#155]
## 你正在使用哪个版本的 nexttrace？

Windows_amd64

## 你看到的异常现象是什么？

Windows11平台，使用时采用本地dns服务(127.0.0.1:53)，nexttrace会报错

## 你期待看到的正常表现是怎样的？

正确利用本地dns解析ip

## 请附上你的命令

nexttrace 1.0.0.1

## 请附上出错时软件输出的错误信息
![image](https://github.com/nxtrace/Ntrace-core/assets/38959826/5491be5b-2e2d-4eb6-b46f-9603bedc174f)

## 是否查询过本仓库wiki有没有类似错误
无

**Comment by tsosunchia** [comment]
你的网络环境是在大陆吗？ 

nslookup api.leo.moe 会显示什么？

**Comment by HXHGTS** [comment]
@tsosunchia 大陆，移动网络
![image](https://github.com/nxtrace/Ntrace-core/assets/38959826/ef10deec-8a97-4327-a2c8-16db3443d8ab)
可能是api.leo.moe解析有问题导致的，谢谢

**Comment by sjlleo** [comment]
Hi HXHGTS,

DNS解析失败的问题让我想起了之前某个 issue 说要开启 pure Go resolver，那个 feature 会让 go 完全接管 DNS 的解析，您目前是禁止了除 127.0.0.1 以外所有 DNS UDP 请求吗？

Thanks!

Best Regards,
Leo Shen

**Comment by HXHGTS** [comment]
@sjlleo 没有，只是设置了系统dns为127.0.0.1和::1

**Comment by sjlleo** [comment]
> @tsosunchia 大陆，移动网络 ![image](https://user-images.githubusercontent.com/38959826/261786180-ef10deec-8a97-4327-a2c8-16db3443d8ab.png) 可能是api.leo.moe解析有问题导致的，谢谢

另外，我看到您似乎在使用本地 IPv6 在提供 DNS 服务，我不确定是否是解析到了 IPv6 导致的 Err，因为使用 pure go resolver 时有些参数（如 DNS Resolver 的 IP）是外部获得的，它可能没有正确解析 IPv6 地址，我需要再回去测试一下。

感谢您的来电，我会在确认问题后尽快回复的，谢谢

**Comment by tsosunchia** [comment]
尝试利用NEXTTRACE_HOSTPORT环境变量强行指定api.leo.moe试试？

**Comment by HXHGTS** [comment]
我用的是xray的dns分流规则，xray核心监听本地53端口提供dns服务，似乎是xray核心无法正确识别这个域名来分流
![image](https://github.com/nxtrace/Ntrace-core/assets/38959826/fb71b139-5ce1-4006-8239-7472af43a2dd)
![image](https://github.com/nxtrace/Ntrace-core/assets/38959826/d99d5181-4210-4373-93a9-388ece75e218)
其余dns能正常解析：
![image](https://github.com/nxtrace/Ntrace-core/assets/38959826/4da928b3-3d91-4841-9d1a-713e6c289191)
我再测试一下

**Comment by tsosunchia** [comment]
既然您本地有xray这类代理，建议您参考
https://github.com/nxtrace/Ntrace-core/wiki
中提到的SOCKS5/HTTP代理。

**Comment by HXHGTS** [comment]
这个锅可能不是nexttrace软件导致的，可能是api域名的锅😂

**Comment by tsosunchia** [comment]
我们的域名在大陆是上了黑名单的

> 这个锅可能不是nexttrace软件导致的，可能是api域名的锅😂

**Comment by HXHGTS** [comment]
解决了，是xray分流列表里默认没有对这个api妥善分流导致的：
![屏幕截图 2023-08-19 163348](https://github.com/nxtrace/Ntrace-core/assets/38959826/f92259b5-2f3d-430e-be99-02384d8bb09d)
![屏幕截图 2023-08-19 163416](https://github.com/nxtrace/Ntrace-core/assets/38959826/f2cb2cca-9fde-4b5d-b45c-e5aaa73d3285)
![屏幕截图 2023-08-19 163525](https://github.com/nxtrace/Ntrace-core/assets/38959826/6ce11237-8f5e-4d5f-8447-e101f9f677d6)
个人怀疑可能是目前的分流规则对.moe这类新后缀的处理有问题
