### ISSUE TITLE
Windows版本exe文件安装失败

### ISSUE THREAD

**Issue by ExinAinx** [nxtrace/NTrace-core#164]
小白一枚，在[Release](https://github.com/nxtrace/Ntrace-V1/releases/latest)页面下载的v1.2.1.1 [nexttrace_windows_amd64.exe](https://github.com/nxtrace/NTrace-V1/releases/download/v1.2.1.1/nexttrace_windows_amd64.exe)文件，在下载盘和C盘分别尝试启动的情况下，均出现命令页一闪而过，从而exe文件无法启动安装，在确认安装VS++库和.NET运行库情况下依旧启动失败，想请教解决方案，以下是cmd启动反馈页面：
![{B126305A-15EA-4A69-937B-B123605B5BEC}](https://github.com/nxtrace/NTrace-core/assets/52076575/11a628ac-4f34-400c-a35a-cef72a42266d)

**Comment by tsosunchia** [comment]
这个仓库是命令行版，你需要在cmd里 通过命令使用
比如/path/to/nexttrace example.com

如果你不擅长用命令行来操作，建议小白朋友去用nexttrace的图形界面版
看这里：https://github.com/Archeb/opentrace

**Comment by ExinAinx** [comment]
> 这个仓库是命令行版，你需要在cmd里 通过命令使用 比如/path/to/nexttrace example.com
> 
> 如果你不擅长用命令行来操作，建议小白朋友去用nexttrace的图形界面版 看这里：https://github.com/Archeb/opentrace

好的，谢谢回复
