### ISSUE TITLE
ip归属地无法显示

### ISSUE THREAD

**Issue by Chenyu550** [nxtrace/NTrace-core#183]
## 你正在使用哪个版本的 nexttrace？

Windows_amd64

## 你看到的异常现象是什么？

![image](https://github.com/nxtrace/NTrace-core/assets/114039435/7732cdc3-50e0-489a-bd57-1ad214fbda74)
前两天还正常的

## 你期待看到的正常表现是怎样的？

正常显示

## 请附上你的命令

nexttrace \*.\*.\*.\*

## 请附上出错时软件输出的错误信息
如上图
## 是否查询过本仓库wiki有没有类似错误
没看到

**Comment by tsosunchia** [comment]
麻烦你将图截全，我需要看源站是哪里

**Comment by Chenyu550** [comment]
> 麻烦你将图截全，我需要看源站是哪里

![image](https://github.com/nxtrace/NTrace-core/assets/114039435/abae38fb-67a2-4fa6-b68e-77ca24c3cfd9)

**Comment by tsosunchia** [comment]
感谢您的反馈，已修复该节点问题，已恢复正常
