### ISSUE TITLE
是否考虑支持mtr

### ISSUE THREAD

**Issue by aliuzzz** [nxtrace/NTrace-core#185]
向opentrace那样，支持mtr选项手动开启或关闭，从而可以将mtr的loss%值一同显示出来？

**Comment by tsosunchia** [comment]
此特性是一直在努力的方向，但不幸的是目前本社区的开发者暂时没有能力在命令行界面实现此特性。

目前已支持了在web页面显示这一风格的结果，也请查看 https://github.com/nxtrace/nexttracewebapi

同时也欢迎大佬来提出PR帮助本项目实现该特性
