### ISSUE TITLE
-F 的时候能否选择哪个地区？

### ISSUE THREAD

**Issue by gdyan2022** [nxtrace/NTrace-core#236]
nexttrace -F 的时候，选择 “国内四网” 默认是北京的四网，是否能加个选项选择其他城市的四网？
谢谢

**Comment by tsosunchia** [comment]
fasttrace 选项里的“全部”这个选项就是啊 里面有北京广州上海等

**Comment by gdyan2022** [comment]
例如我只想看 上海的四网呢？ 
虽然是个很冷门的需求。。。

**Comment by haima3** [comment]
那你直接到时候把上海的那部分筛选出来就好了呀，比如把结果筛选出上海的那部分重定向到文件

________________________________

**Comment by gdyan2022** [comment]
也行吧，谢谢
