### ISSUE TITLE
无法显示路由信息

### ISSUE THREAD

**Issue by Bryan2333** [nxtrace/NTrace-core#239]
## 本项目是基于Linux/macOS的，请确认您遇到的问题是否在Linux或macOS上存在。
是

## 你正在使用哪个版本的 nexttrace？
Linux build from source

## 你看到的异常现象是什么？
除了开始的节点和结束节点，其他节点的路由信息无法显示

![_20240510_175042.webp](https://s2.loli.net/2024/05/10/CMLJlNozRxr4nje.webp)

## 你期待看到的正常表现是怎样的？
正常显示路由信息

## 请附上你的命令
```
sudo nexttrace america.archive.pkgbuild.com
```

然后选IPv4地址

## 请附上出错时软件输出的错误信息
无错误输出

**Comment by tsosunchia** [comment]
可能是你网络中防火墙的问题

**Comment by Bryan2333** [comment]
我感觉不太可能，我这边直接使用traceroute跟踪了一下对应的IP，是可以显示出来的。
![_20240510_203921.webp](https://s2.loli.net/2024/05/10/aNbS1DHXi82jxEP.webp)

**Comment by tsosunchia** [comment]
你是在什么环境下运行的

**Comment by Bryan2333** [comment]
我的系统是Arch Linux，然后用的是AUR上的这个包[nexttrace](https://aur.archlinux.org/packages/nexttrace)

我电脑上用Nftables配了一个TProxy的透明代理。我尝试过把透明代理的规则删掉，但还是没办法显示出中间的路由信息。

**Comment by tsosunchia** [comment]
建议抓一下包

**Comment by Bryan2333** [comment]
我用wireshark抓了ICMP的包。

这个是开启透明代理时的情况，nexttrace除了开始节点和结束节点以外的节点都显示不出来。
![屏幕截图_20240510_205249](https://github.com/nxtrace/NTrace-core/assets/31512600/c32a5d76-7177-41c7-b930-ef481a8a5514)

这个是关闭透明代理时的情况，nexttrace可以显示出部分路由。
![屏幕截图_20240510_205547](https://github.com/nxtrace/NTrace-core/assets/31512600/53aa3817-d807-4a1e-88cb-bbb3e902f725)

**Comment by tsosunchia** [comment]
大概看了一下，
这个问题，我觉得如果你去询问你所使用的代理软件的issue区可能更有用

**Comment by tsosunchia** [comment]
大概是你的nft哪里配的有问题

**Comment by tsosunchia** [comment]
> 我感觉不太可能，我这边直接使用traceroute跟踪了一下对应的IP，是可以显示出来的。
> 
> ![_20240510_203921.webp](https://s2.loli.net/2024/05/10/aNbS1DHXi82jxEP.webp)

你可以试试

traceroute --icmp

看看能不能正常trace

nextttace默认使用icmp

**Comment by Bryan2333** [comment]
我试了，果然不行。我查了一下，Linux下traceroute是走UDP协议，默认端口是33434。

我这边nexttrace改用UDP协议加上33434端口查询就好了，默认的53端口不行。

![屏幕截图_20240510_212525](https://github.com/nxtrace/NTrace-core/assets/31512600/9e2699a0-0f10-4d51-9d2a-9fbc5a5afcc4)
