### ISSUE TITLE
无法显示路由信息

### ISSUE THREAD

**Issue by enokoneko** [nxtrace/NTrace-core#251]
## 本项目是基于Linux/macOS的，请确认您遇到的问题是否在Linux或macOS上存在。
是

## 你正在使用哪个版本的 nexttrace？
macOS
NextTrace 1.3.1 2024-05-30T04:26:46Z brew

## 你看到的异常现象是什么？

<img width="588" alt="image" src="https://github.com/user-attachments/assets/fb81880e-4f9c-4ceb-a798-8aa17ce12b2d">

## 你期待看到的正常表现是怎样的？
正常显示路由信息

## 请附上你的命令
```
nexttrace 1.1.1.1
```

## 请附上出错时软件输出的错误信息
无错误输出

## 是否查询过本仓库wiki有没有类似错误
https://github.com/nxtrace/NTrace-core/issues/239
看到有相似情况，有人说可能是防火墙的问题，我尝试用traceroute 1.1.1.1确实也显示不全，但我不具备相关知识，不知道如何应对这种情况。尝试过关闭路由器防火墙或开启所有端口转发，但不见效。
<img width="460" alt="image" src="https://github.com/user-attachments/assets/31d9cc58-9f69-4da8-8c7f-278d37fb0e26">

**Comment by laloe74** [comment]
一样的情况

**Comment by laloe74** [comment]
关掉代理，再连接手机热点解决了。不知道是什么问题。

**Comment by enokoneko** [comment]
我还是没解决，但网页版可用。
https://www.tokototech.com/

**Comment by enokoneko** [comment]
另外我剛發現測IPv6也沒有問題，能正確顯示。

**Comment by tsosunchia** [comment]
楼上使用的是什么类型代理？

如果是tun形式，推荐在代理软件开启时设置`--dev`参数指定网卡接口

**Comment by tsosunchia** [comment]
另外建议使用 tcpdump or wireshark 进行抓包，看看不显示的那么 HOPS 有没有回包，如果没有，那大概就是本地网络的防火墙配置问题了。

**Comment by tsosunchia** [comment]
可以测试一下其他路由软件，如`MTR`看看是否正常

**Comment by laloe74** [comment]
我是Mac Sonoma 14.6.1，代理工具是Shadowrocket，Global Routing: Config

1. 当代理模式是HTTP，端口1082，地址是198.18.0.3 (Default Tun HTTP Proxy Server)
```
$ nexttrace 1.1.1.1
NextTrace 1.3.1 2024-05-30T04:26:46Z brew
[NextTrace API] preferred API IP - 198.18.0.62 - 2073.02ms - DMIT.LAX
IP Geo Data Provider: LeoMoeAPI
traceroute to 1.1.1.1, 30 hops max, 52 bytes payload
下面一直卡住无信息，光标闪烁
```

2. 当代理模式是HTTP，端口1082，地址是127.0.0.1 （Loopback HTTP Proxy Server）
```
$ nexttrace 1.1.1.1
NextTrace 1.3.1 2024-05-30T04:26:46Z brew
[NextTrace API] preferred API IP - 198.18.0.62 - 1138.29ms - DMIT.LAX
IP Geo Data Provider: LeoMoeAPI
traceroute to 1.1.1.1, 30 hops max, 52 bytes payload
下面一直卡住无信息，光标闪烁
```

3. 当代理模式是None（TUN Mode），端口1082，地址是127.0.0.1 （Loopback HTTP Proxy Server）
```
$ nexttrace 1.1.1.1
NextTrace 1.3.1 2024-05-30T04:26:46Z brew
[NextTrace API] preferred API IP - 198.18.0.62 - 1003.05ms - DMIT.LAX
IP Geo Data Provider: LeoMoeAPI
traceroute to 1.1.1.1, 30 hops max, 52 bytes payload
下面一直卡住无信息，光标闪烁
```

4. 当代理模式是None（TUN Mode），端口1082，地址是198.18.0.3 (Default Tun HTTP Proxy Server)
```
$ nexttrace 1.1.1.1
NextTrace 1.3.1 2024-05-30T04:26:46Z brew
[NextTrace API] preferred API IP - 198.18.0.62 - 1367.17ms - DMIT.LAX
IP Geo Data Provider: LeoMoeAPI
traceroute to 1.1.1.1, 30 hops max, 52 bytes payload
下面一直卡住无信息，光标闪烁
```

5. 当关闭Shadowrocket时，连接Wifi时
```
$ nexttrace 1.1.1.1
NextTrace 1.3.1 2024-05-30T04:26:46Z brew
[NextTrace API] preferred API IP - 46.3.104.246 - 190.37ms - Misaka.HKG TMP
IP Geo Data Provider: LeoMoeAPI
traceroute to 1.1.1.1, 30 hops max, 52 bytes payload
1   192.168.1.1     *                         RFC1918          
                                              3.50 ms / 2.68 ms / 3.03 ms
2   100.71.0.1      *                         RFC6598          
                                              4.82 ms / 4.58 ms / 4.86 ms
3   *
4   *
5   *
6   *
7   *
8   *
9   *
10  *
11  1.1.1.1         AS13335                   CLOUDFLARE.COM    cloudflare.com 
    1.1.1.1.in-addr.arpa                      * ms / 970.48 ms / 959.99 ms
MapTrace URL: 没有需要绘制的数据。
```

6. 当关闭Shadowrocket时，连接手机热点时
```
一切正常
```

**Comment by tsosunchia** [comment]
> 我是Mac Sonoma 14.6.1，代理工具是Shadowrocket，Global Routing: Config
> 
> 1. 当代理模式是HTTP，端口1082，地址是198.18.0.3 (Default Tun HTTP Proxy Server)
> 
> ```
> $ nexttrace 1.1.1.1
> NextTrace 1.3.1 2024-05-30T04:26:46Z brew
> [NextTrace API] preferred API IP - 198.18.0.62 - 2073.02ms - DMIT.LAX
> IP Geo Data Provider: LeoMoeAPI
> traceroute to 1.1.1.1, 30 hops max, 52 bytes payload
> 下面一直卡住无信息，光标闪烁
> ```
> 
> 2. 当代理模式是HTTP，端口1082，地址是127.0.0.1 （Loopback HTTP Proxy Server）
> 
> ```
> $ nexttrace 1.1.1.1
> NextTrace 1.3.1 2024-05-30T04:26:46Z brew
> [NextTrace API] preferred API IP - 198.18.0.62 - 1138.29ms - DMIT.LAX
> IP Geo Data Provider: LeoMoeAPI
> traceroute to 1.1.1.1, 30 hops max, 52 bytes payload
> 下面一直卡住无信息，光标闪烁
> ```
> 
> 3. 当代理模式是None（TUN Mode），端口1082，地址是127.0.0.1 （Loopback HTTP Proxy Server）
> 
> ```
> $ nexttrace 1.1.1.1
> NextTrace 1.3.1 2024-05-30T04:26:46Z brew
> [NextTrace API] preferred API IP - 198.18.0.62 - 1003.05ms - DMIT.LAX
> IP Geo Data Provider: LeoMoeAPI
> traceroute to 1.1.1.1, 30 hops max, 52 bytes payload
> 下面一直卡住无信息，光标闪烁
> ```
> 
> 4. 当代理模式是None（TUN Mode），端口1082，地址是198.18.0.3 (Default Tun HTTP Proxy Server)
> 
> ```
> $ nexttrace 1.1.1.1
> NextTrace 1.3.1 2024-05-30T04:26:46Z brew
> [NextTrace API] preferred API IP - 198.18.0.62 - 1367.17ms - DMIT.LAX
> IP Geo Data Provider: LeoMoeAPI
> traceroute to 1.1.1.1, 30 hops max, 52 bytes payload
> 下面一直卡住无信息，光标闪烁
> ```
> 
> 5. 当关闭Shadowrocket时，连接Wifi时
> 
> ```

打开代理软件是，使用`--dev`指定接口看看

> $ nexttrace 1.1.1.1
> NextTrace 1.3.1 2024-05-30T04:26:46Z brew
> [NextTrace API] preferred API IP - 46.3.104.246 - 190.37ms - Misaka.HKG TMP
> IP Geo Data Provider: LeoMoeAPI
> traceroute to 1.1.1.1, 30 hops max, 52 bytes payload
> 1   192.168.1.1     *                         RFC1918          
>                                               3.50 ms / 2.68 ms / 3.03 ms
> 2   100.71.0.1      *                         RFC6598          
>                                               4.82 ms / 4.58 ms / 4.86 ms
> 3   *
> 4   *
> 5   *
> 6   *
> 7   *
> 8   *
> 9   *
> 10  *
> 11  1.1.1.1         AS13335                   CLOUDFLARE.COM    cloudflare.com 
>     1.1.1.1.in-addr.arpa                      * ms / 970.48 ms / 959.99 ms
> MapTrace URL: 没有需要绘制的数据。
> ```
> 
> 6. 当关闭Shadowrocket时，连接手机热点时
> 
> ```
> 一切正常
> ```

看起来你的local isp 或本地网络可能禁止了traceroute，这个需要抓包证实

**Comment by SukkaW** [comment]
> 如果是tun形式，推荐在代理软件开启时设置`--dev`参数指定网卡接口

Darwin 24.0.0 arm64 / macOS 15.0
NextTrace 1.3.4 2024-09-10T03:19:06Z brew

`--dev` 参数不起作用，即使指定 `--dev en0` 追踪依然从 TUN 发出:

<img width="690" alt="image" src="https://github.com/user-attachments/assets/09d6909c-a8fd-4605-8259-014ba5b48ebf">

**Comment by tsosunchia** [comment]
> > 如果是tun形式，推荐在代理软件开启时设置`--dev`参数指定网卡接口
> 
> Darwin 24.0.0 arm64 / macOS 15.0 NextTrace 1.3.4 2024-09-10T03:19:06Z brew
> 
> `--dev` 参数不起作用，即使指定 `--dev en0` 追踪依然从 TUN 发出:
> 
> <img alt="image" width="690" src="https://private-user-images.githubusercontent.com/40715044/367663809-09d6909c-a8fd-4605-8259-014ba5b48ebf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NzMyNzIsIm5iZiI6MTcyNjQ3Mjk3MiwicGF0aCI6Ii80MDcxNTA0NC8zNjc2NjM4MDktMDlkNjkwOWMtYThmZC00NjA1LTgyNTktMDE0YmE1YjQ4ZWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDA3NDkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkOTQzOGVlMzJmZGRkN2FkNTc2MTNkNjRiYjlhMTJhYTZiZDE0NWM4MGQ4OWU1NWZlMGY4MzQ0MDQwNGM0NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ujmAdwBLn3qyykm-YH9OaFCTO3LDebcT_8vbN0b8bRk">

如果使用-s指定源ip呢，因为我手头没有最新预览版的机器所以没法排查

**Comment by SukkaW** [comment]
> > > 如果是tun形式，推荐在代理软件开启时设置`--dev`参数指定网卡接口
> > 
> > 
> > Darwin 24.0.0 arm64 / macOS 15.0 NextTrace 1.3.4 2024-09-10T03:19:06Z brew
> > `--dev` 参数不起作用，即使指定 `--dev en0` 追踪依然从 TUN 发出:
> > <img alt="image" width="690" src="https://private-user-images.githubusercontent.com/40715044/367663809-09d6909c-a8fd-4605-8259-014ba5b48ebf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NzMyNzIsIm5iZiI6MTcyNjQ3Mjk3MiwicGF0aCI6Ii80MDcxNTA0NC8zNjc2NjM4MDktMDlkNjkwOWMtYThmZC00NjA1LTgyNTktMDE0YmE1YjQ4ZWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDA3NDkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkOTQzOGVlMzJmZGRkN2FkNTc2MTNkNjRiYjlhMTJhYTZiZDE0NWM4MGQ4OWU1NWZlMGY4MzQ0MDQwNGM0NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ujmAdwBLn3qyykm-YH9OaFCTO3LDebcT_8vbN0b8bRk">
> 
> 如果使用-s指定源ip呢，因为我手头没有最新预览版的机器所以没法排查

使用 `--source` 参数以后第一跳依旧是 TUN：

<img width="782" alt="image" src="https://github.com/user-attachments/assets/c9fbd0b1-41ef-4aae-967f-6b396bf33c64">

**Comment by tsosunchia** [comment]
> > > > 如果是tun形式，推荐在代理软件开启时设置`--dev`参数指定网卡接口
> > > 
> > > 
> > > Darwin 24.0.0 arm64 / macOS 15.0 NextTrace 1.3.4 2024-09-10T03:19:06Z brew
> > > `--dev` 参数不起作用，即使指定 `--dev en0` 追踪依然从 TUN 发出:
> > > <img alt="image" width="690" src="https://private-user-images.githubusercontent.com/40715044/367663809-09d6909c-a8fd-4605-8259-014ba5b48ebf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NzMyNzIsIm5iZiI6MTcyNjQ3Mjk3MiwicGF0aCI6Ii80MDcxNTA0NC8zNjc2NjM4MDktMDlkNjkwOWMtYThmZC00NjA1LTgyNTktMDE0YmE1YjQ4ZWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDA3NDkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkOTQzOGVlMzJmZGRkN2FkNTc2MTNkNjRiYjlhMTJhYTZiZDE0NWM4MGQ4OWU1NWZlMGY4MzQ0MDQwNGM0NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ujmAdwBLn3qyykm-YH9OaFCTO3LDebcT_8vbN0b8bRk">
> > 
> > 
> > 如果使用-s指定源ip呢，因为我手头没有最新预览版的机器所以没法排查
> 
> 使用 `--source` 参数以后第一跳依旧是 TUN：
> 
> <img alt="image" width="782" src="https://private-user-images.githubusercontent.com/40715044/367682472-c9fbd0b1-41ef-4aae-967f-6b396bf33c64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NzQxMTcsIm5iZiI6MTcyNjQ3MzgxNywicGF0aCI6Ii80MDcxNTA0NC8zNjc2ODI0NzItYzlmYmQwYjEtNDFlZi00YWFlLTk2N2YtNmIzOTZiZjMzYzY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDA4MDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhYmU5ZTBiOWQ0NGZhMTJmNzVlZDAzMmU1NjM5OTA1NTEwNmI0MWYwY2Y5NWZhNTE5ZjEwMzk1MTMxYzlkNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O14rvWVdlL4u9shIfwjZe5dQmp7Jzqi74uGlfOOexv8">

有可能是最新版系统和golang net库的兼容性问题，暂时没有解决方案

**Comment by tsosunchia** [comment]
> 没有设置 参数就是目标域名。是需要额外指定什么吗 ？ 会卡在 
> 
> traceroute to 47.74.xx.xx, 30 hops max, 52 bytes payload, ICMP mode

--help获取更多帮助，使用中的困惑可以在discussion区发帖
