### ISSUE TITLE
[功能请求] 字体颜色适配白色背景

### ISSUE THREAD

**Issue by laloe74** [nxtrace/NTrace-core#267]
**ls your feature request related to a problem? Please describe.**
Mac的终端背景颜色有黑白两种模式，会根据白天/夜晚自动切换。当前nexttrace的字体颜色在白色背景下很难看清。

**Describe the solution you'd like**
字体颜色适配终端的白色背景。

**Describe alternatives you've considered**
如果不能根据系统主题设置自动切换字体颜色，有可能的解决方案为：

1. 为黑色/白色背景设置两种字体颜色主题，可以手动切换。
2. 设置一种中性字体颜色，使字体无论在白色还是黑色背景下都能正确显示。
3. 增加一个配置文件，让用户自定义字体颜色。

**Additional context**
无

**Comment by tsosunchia** [comment]
暂时可以使用` -C` 参数，至于 `github.com/fatih/color` 的调用方式后续可能会优化
