### ISSUE TITLE
Windows 在某些环境只能 print 出来星号 *

### ISSUE THREAD

**Issue by grdll** [nxtrace/NTrace-core#269]
## 本项目是基于Linux/macOS的，请确认您遇到的问题是否在Linux或macOS上存在。
暂时没发现

## 你正在使用哪个版本的 nexttrace？
基于 [4ae9d8e](https://github.com/nxtrace/NTrace-core/commit/4ae9d8ece137cc11edc2309e31a64bfa64378674) 删除 Network Error 后的自编译版本 (原版一样的问题)

## 你看到的异常现象是什么？
![Snipaste_2024-10-29_00-28-22](https://github.com/user-attachments/assets/6fc1749c-1f82-4197-b4bf-d094e34d0922)

## 抓包
![Snipaste_2024-10-29_00-19-45](https://github.com/user-attachments/assets/36c26ed6-3538-4978-8fe1-9a6661cd8624)

除了 Identifier 与其它程序不同，没有发现其它异样，抓包看，就连回复都收到了，就是不知道为什么只 print 星号

## 系统版本比较，供参考 ( Y 有问题 N 没问题)
1. Windows 11 Enterprise 24H2 x v4 NAT (N)
2. Windows 11 Enterprise 22H2 x v4 NAT (N)
3. Windows 10 Pro 22H2 x v4 NAT (Y)
4. Windows 10 Enterprise 22H2 x v4 NAT (Y)
5. Windows Server 2019 Datacenter 1809 x v4 NAT (Y)
6. Windows Server 2016 Datacenter 1607 x v4 公网 (N)
7. Windows Server 2016 Datacenter 1607 x v4 NAT (N)
8. Windows Server 2012 R2 Datacenter x v4 公网 (N)
9. Windows Server 2012 R2 Datacenter x v6 公网 (Y)

**Comment by tsosunchia** [comment]
请确认你的防火墙配置，可以参考repo wiki

**Comment by tsosunchia** [comment]
如有其他问题，欢迎再次提交issue
