### ISSUE TITLE
[请教] 关于官网统计数据的来源隐忧

### ISSUE THREAD

**Issue by edwinjhlee** [nxtrace/NTrace-core#273]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

你好，nexttrace 社区的朋友，

在官网上有 

```
NextTrace has been used
for 2572.3K+ times
```

请问这个数字是如何统计出来的？是否能介绍下下，否则可能会引起用户的一些安全隐私的忧虑 ？

**Describe alternatives you've considered**

**Additional context**

**Comment by tsosunchia** [comment]
调用 NextTrace 官方 API 获取 GEOIP 信息时，会进行 POW 鉴权，官网的次数信息就是统计的成功鉴权次数。

见 https://github.com/nxtrace/NTrace-core/blob/main/pow/pow.go

使用第三方 API 或离线状态时的次数不被统计。

**Comment by edwinjhlee** [comment]
明白 ～ 谢谢作者解答。
