### ISSUE TITLE
在 Linux 和在 macOS 下编译 darwin (macOS) 版本都会出现错误

### ISSUE THREAD

**Issue by grdll** [nxtrace/NTrace-core#281]
## 命令

`(CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o build/nexttrace_macos_arm64)`

## 错误信息

```
# github.com/nxtrace/NTrace-core
link: github.com/nxtrace/NTrace-core/trace/internal: invalid reference to net.internetSocket
```

## Go 版本
`go version go1.23.4 linux/amd64`
`go version go1.23.4 darwin/arm64`

**Comment by tsosunchia** [comment]
请使用Go1.22
